config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "homes#top"
  get "home/about" => "homes#about"
  get '/search' => 'searches#search', as: 'search'


  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :followings, :followers
    end
  resource :relationships, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
	has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
	has_many :followings, through: :follower, source: :followed
  has_many :followers, through: :followed, source: :follower

  attachment :profile_image, destroy: false

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  
  # ユーザーをフォローする
  def follow(other_user)
    unless self == other_user
    follower.create(followed_id: other_user.id)
    end
  end
  # ユーザーのフォローを外す
  def unfollow(other_user)
    follower.find_by(followed_id: other_user.id).destroy
  end
  # フォロー確認をおこなう
  def following?(other_user)
    followings.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% unless current_user == user %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
		<th>follows</th>
		<th><%= link_to user.followings.count, followings_user_path(user) %></th>
	</tr>
	<tr>
		<th>followers</th>
		<th><%= link_to user.followers.count, followers_user_path(user) %></th>
	</tr>
</table>
</table>

<div class="row">
	<% unless current_user == user %>
	  <% if current_user.following?(user) %>
	    <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary mb-3" %>
	  <% else %>
	    <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class: "btn btn-success mb-3" %>
	  <% end %>
	<% end %>
</div>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
	<div class="row">
		<h2>Follower Users</h2>
		<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
						<td><%= user.name %></td>
						<td><span>フォロー数：</span><%= user.followings.count %></td>
						<td><span>フォロワー数：</span><%= user.followers.count %></td>
						<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
	</div>
</div>

app/views/users/followings.html.erb
<div class="container">
	<div class="row">
		<h2>Follow Users</h2>
		<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
						<td><%= user.name %></td>
						<td><span>フォロー数：</span><%= user.followings.count %></td>
						<td><span>フォロワー数：</span><%= user.followers.count %></td>
						<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
	</div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>